name: Github-action-practice

on:
  push:
    branches: [first-pipeline-1]
    paths:
    - 'factoriel.py'
    - 'lint_test.py'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-alpine
      options: --cpus 1
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2
      - name: Integration test
        run: python factorial.py
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Test which OS the runner is using
      run: echo "This job is now running on ${{ runner.os }} server hosted by github."
    - name: Which branch is checked out
      run: echo "The name of the branch is ${{ github.ref }} in repository ${{ github.repository }}"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: After actions
      run: echo "The ${{ github.repository }} has cloned to the runner."
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Build container
      run: |
        echo "Building docker container ..."
        sleep 60
        echo "Docker container built successfully"
    - name: Deploy
      run: |
        echo "Deploying to our imaginary cluster"
        sleep 60
        echo "App has been deployed successfully."
    - run: echo "This job's status is ${{ job.status }}."
